version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    # volumes:
    #   - /etc/localtime:/etc/localtime
    #   - /home/mycontainers/myrabbit/rabbitmq:/var/lib/rabbitmq
    # network_mode: mynetwork
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
